from __future__ import annotations

import json
import logging
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

from anthropic import Anthropic

from .config import Config, ProcessingMode
from .fetch import FetchedEmail
from .readability import evaluate_human_readability
from .rule_digest import (
    RuleTopic,
    compute_rule_dedup_assignments,
    extract_rule_topics,
    rule_output_is_sufficient,
)

log = logging.getLogger(__name__)

STAGE1_MAX_OUTPUT_TOKENS = 8192
STAGE2_MAX_OUTPUT_TOKENS = 4096
TOKEN_RE = re.compile(r"[a-zA-Z0-9ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]{3,}")
SENDER_PROFILE_FILE = "sender_profiles.json"
TRANSLATION_SENDER_HINTS = ("exante", "naval")
SEMANTIC_SEGMENTATION_SENDERS = ("redakcja xyz",)
ENGLISH_HINT_WORDS = {
    "the", "and", "with", "from", "into", "this", "that", "will", "market", "markets",
    "global", "policy", "growth", "inflation", "investors", "earnings", "outlook", "update",
    "weekly", "daily", "insights", "economy", "rates", "stocks", "bonds",
}


def _sanitize_json_control_chars(raw: str) -> str:
    """Best-effort repair of malformed JSON generated by the model."""
    out: list[str] = []
    in_string = False
    escaped = False
    i = 0
    n = len(raw)

    while i < n:
        ch = raw[i]
        if in_string:
            if escaped:
                out.append(ch)
                escaped = False
                i += 1
                continue
            if ch == "\\":
                out.append(ch)
                escaped = True
                i += 1
                continue
            if ch == "\"":
                # If quote is not followed by a valid delimiter, treat it as
                # an unescaped quote inside the string and escape it.
                j = i + 1
                while j < n and raw[j] in (" ", "\t", "\r", "\n"):
                    j += 1
                next_token = raw[j] if j < n else ""
                if next_token not in (",", "}", "]", ":"):
                    out.append("\\\"")
                    i += 1
                    continue
                out.append(ch)
                in_string = False
                i += 1
                continue
            if ch == "\n":
                out.append("\\n")
                i += 1
                continue
            if ch == "\r":
                out.append("\\r")
                i += 1
                continue
            if ch == "\t":
                out.append("\\t")
                i += 1
                continue
            out.append(ch)
            i += 1
            continue

        out.append(ch)
        if ch == "\"":
            in_string = True
        i += 1

    return "".join(out)


STAGE1_SYSTEM_PROMPT = """Jesteś asystentem przetwarzającym pojedynczy newsletter. Twoim zadaniem jest wyekstrahować wszystkie tematy i stworzyć zwięzłe podsumowania napisane własnymi słowami po polsku.

KRYTYCZNE ZASADY:
1. ZAWSZE czytaj PEŁNĄ treść newslettera od początku do końca. NIE wolno bazować na pierwszych akapitach. Najważniejsze tematy w Morning Brew, TLDR, Stratechery, Pucek itp. często są DALEKO w treści.
2. NIGDY nie kopiuj dosłownie — zawsze przetwarzaj i streszczaj własnymi słowami po polsku.
3. KAŻDY temat MUSI mieć link jeśli jest dostępny. Sprawdź zarówno tekst newslettera (linki w formacie [tekst](url)) jak i listę raw_links. Linki trackingowe (click.*, link.*) są OK.
4. Zidentyfikuj WSZYSTKIE osobne tematy. Newslettery zbiorcze mają wiele tematów; jednotematyczne — jeden, ale i tak streszczaj.
5. Każdy temat: 2-3 zdania, konkretne liczby/fakty.
6. Tekst linka = nazwa źródła (np. "Bloomberg", "TechCrunch") lub krótki opis, NIE surowy URL.

Zwróć wynik wyłącznie przez wywołanie narzędzia `emit_newsletter_topics`."""

STAGE1_RETRY_SYSTEM_PROMPT = """Ponawiasz ekstrakcję tematów z pojedynczego newslettera po nieudanej pierwszej próbie.

KRYTYCZNE ZASADY:
1. Zwróć poprawne wywołanie `emit_newsletter_topics`.
2. Pole `topics` MUSI być tablicą obiektów, NIGDY stringiem.
3. Każdy obiekt tematu ma mieć: `title`, `summary`, `links`.
4. Jeśli nie jesteś pewny linka, zostaw `links` jako pustą listę, ale nadal zwróć temat.
5. Lepiej zwrócić krótsze podsumowanie niż uszkodzić format.
"""


STAGE1_TOOL_SCHEMA = {
    "name": "emit_newsletter_topics",
    "description": "Zwraca wyekstrahowane tematy z jednego newslettera.",
    "input_schema": {
        "type": "object",
        "properties": {
            "sender": {"type": "string", "description": "Nazwa nadawcy (skopiuj z wejścia)"},
            "subject": {"type": "string", "description": "Temat maila (skopiuj z wejścia)"},
            "topics": {
                "type": "array",
                "description": "Lista wszystkich tematów z newslettera",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Krótki tytuł tematu po polsku"},
                        "summary": {"type": "string", "description": "2-3 zdania streszczenia własnymi słowami"},
                        "links": {
                            "type": "array",
                            "description": "1-3 najważniejsze linki do tego tematu",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "text": {"type": "string"},
                                    "url": {"type": "string"},
                                },
                                "required": ["text", "url"],
                            },
                        },
                    },
                    "required": ["title", "summary", "links"],
                },
            },
        },
        "required": ["sender", "subject", "topics"],
    },
}


STAGE2_SYSTEM_PROMPT = """Jesteś asystentem identyfikującym duplikaty tematów między newsletterami danego dnia.

Otrzymasz kompaktowe JSON z tytułami i streszczeniami tematów ze wszystkich newsletterów. Twoim zadaniem jest znaleźć tematy, które dotyczą dokładnie tego samego zdarzenia/artykułu i oznaczyć je jako duplikaty.

ZASADY:
1. Temat jest duplikatem tylko jeśli dotyczy DOKŁADNIE tego samego konkretnego zdarzenia, artykułu lub faktu.
2. Ogólne tematy z tej samej branży NIE są duplikatami (np. dwa artykuły o AI w ogóle to nie duplikat).
3. Ustaw `duplicate_of_newsletter_idx` na wartość `newsletter_idx` newslettera, w którym dany temat pojawił się PO RAZ PIERWSZY (niższy indeks = wcześniejszy newsletter).
4. Jeśli nie ma żadnych duplikatów, zwróć pustą tablicę `assignments`.
5. Nie zmieniaj treści tematów — tylko oznaczaj duplikaty.

Zwróć wynik wyłącznie przez wywołanie narzędzia `emit_dedup_assignments`."""


STAGE2_TOOL_SCHEMA = {
    "name": "emit_dedup_assignments",
    "description": "Oznacza duplikaty tematów między newsletterami.",
    "input_schema": {
        "type": "object",
        "properties": {
            "assignments": {
                "type": "array",
                "description": "Lista tematów, które są duplikatami. Pusta tablica jeśli brak duplikatów.",
                "items": {
                    "type": "object",
                    "properties": {
                        "newsletter_idx": {
                            "type": "integer",
                            "description": "Indeks newslettera zawierającego duplikat (wartość newsletter_idx z wejścia)",
                        },
                        "topic_idx": {
                            "type": "integer",
                            "description": "Indeks tematu w tym newsletterze (0-based)",
                        },
                        "duplicate_of_newsletter_idx": {
                            "type": "integer",
                            "description": "Indeks newslettera, w którym temat pojawił się po raz PIERWSZY",
                        },
                    },
                    "required": ["newsletter_idx", "topic_idx", "duplicate_of_newsletter_idx"],
                },
            },
        },
        "required": ["assignments"],
    },
}

TOPICS_REPAIR_SYSTEM_PROMPT = """Otrzymasz tekst, który miał być JSON-em z listą tematów newslettera, ale może być uszkodzony składniowo.
Napraw go i zwróć poprawną strukturę danych.

Zasady:
1. Nie dodawaj nowych tematów ani faktów.
2. Zachowaj sens oryginalnych tytułów i streszczeń.
3. Jeśli pole links jest nieczytelne, zwróć pustą listę.
4. Zwróć wynik wyłącznie przez narzędzie `emit_repaired_topics`.
"""

TOPICS_REPAIR_TOOL_SCHEMA = {
    "name": "emit_repaired_topics",
    "description": "Zwraca poprawną listę tematów po naprawie uszkodzonego JSON-a.",
    "input_schema": {
        "type": "object",
        "properties": {
            "topics": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "summary": {"type": "string"},
                        "links": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "text": {"type": "string"},
                                    "url": {"type": "string"},
                                },
                                "required": ["text", "url"],
                            },
                        },
                    },
                    "required": ["title", "summary", "links"],
                },
            },
        },
        "required": ["topics"],
    },
}


@dataclass
class DigestTopic:
    title: str
    summary: str
    links: list[dict]
    duplicate_of: int | None = None


@dataclass
class DigestNewsletter:
    sender: str
    subject: str
    topics: list[DigestTopic]
    original_index: int = -1
    estimated_cost_usd: float = 0.0
    stage1_input_tokens: int = 0
    stage1_output_tokens: int = 0
    processed_with: str = "llm"


@dataclass
class Digest:
    date: str
    newsletters: list[DigestNewsletter]
    processing_mode: ProcessingMode = "llm-only"

    @property
    def topic_count(self) -> int:
        return sum(len(n.topics) for n in self.newsletters)

    @property
    def duplicate_count(self) -> int:
        return sum(1 for n in self.newsletters for t in n.topics if t.duplicate_of is not None)

    @property
    def estimated_cost_usd(self) -> float:
        return sum(n.estimated_cost_usd for n in self.newsletters)


def _estimate_cost_usd(
    input_tokens: int,
    output_tokens: int,
    in_per_mtok: float,
    out_per_mtok: float,
    cache_write_tokens: int = 0,
    cache_read_tokens: int = 0,
    cache_write_per_mtok: float = 0.0,
    cache_read_per_mtok: float = 0.0,
) -> float:
    return (
        (input_tokens / 1_000_000.0) * in_per_mtok
        + (output_tokens / 1_000_000.0) * out_per_mtok
        + (cache_write_tokens / 1_000_000.0) * cache_write_per_mtok
        + (cache_read_tokens / 1_000_000.0) * cache_read_per_mtok
    )


def _repair_topics_with_llm(
    client: Anthropic,
    cfg: Config,
    raw_topics: str,
    idx: int,
    sender: str,
) -> tuple[list[dict], int, int, float]:
    """LLM fallback for malformed topics JSON strings."""
    log.warning("Stage1 idx=%d sender=%r: attempting LLM repair for malformed topics JSON", idx, sender)
    try:
        response = client.messages.create(
            model=cfg.anthropic_model_stage2,
            max_tokens=2048,
            system=[{"type": "text", "text": TOPICS_REPAIR_SYSTEM_PROMPT}],
            tools=[TOPICS_REPAIR_TOOL_SCHEMA],
            tool_choice={"type": "tool", "name": "emit_repaired_topics"},
            messages=[{"role": "user", "content": raw_topics}],
            timeout=120,
        )
    except Exception as exc:
        log.warning(
            "Stage1 idx=%d sender=%r: repair call failed (%s) — continuing without repair",
            idx,
            sender,
            type(exc).__name__,
        )
        return [], 0, 0, 0.0
    usage_in = int(getattr(response.usage, "input_tokens", 0) or 0)
    usage_out = int(getattr(response.usage, "output_tokens", 0) or 0)
    usage_cache_write = int(getattr(response.usage, "cache_creation_input_tokens", 0) or 0)
    usage_cache_read = int(getattr(response.usage, "cache_read_input_tokens", 0) or 0)
    repair_cost = _estimate_cost_usd(
        usage_in,
        usage_out,
        cfg.stage2_input_usd_per_mtok,
        cfg.stage2_output_usd_per_mtok,
        cache_write_tokens=usage_cache_write,
        cache_read_tokens=usage_cache_read,
        cache_write_per_mtok=cfg.stage2_cache_write_usd_per_mtok,
        cache_read_per_mtok=cfg.stage2_cache_read_usd_per_mtok,
    )
    log.info(
        "Stage1 repair response: idx=%d sender=%r usage_in=%d usage_out=%d est_cost_usd=%.6f",
        idx,
        sender,
        usage_in,
        usage_out,
        repair_cost,
    )
    tool_use = next((b for b in response.content if getattr(b, "type", None) == "tool_use"), None)
    if tool_use is None:
        log.warning("Stage1 idx=%d sender=%r: repair call returned no tool_use", idx, sender)
        return [], usage_in, usage_out, repair_cost
    topics = (tool_use.input or {}).get("topics", []) or []
    if isinstance(topics, str):
        try:
            topics = json.loads(topics)
        except json.JSONDecodeError:
            log.warning("Stage1 idx=%d sender=%r: repair call returned non-parseable string topics", idx, sender)
            topics = []
    if isinstance(topics, list):
        return topics, usage_in, usage_out, repair_cost
    log.warning("Stage1 idx=%d sender=%r: repair call returned non-list topics type=%s", idx, sender, type(topics).__name__)
    return [], usage_in, usage_out, repair_cost


def _build_stage1_message(email: FetchedEmail) -> str:
    parts = [
        f"Nadawca: {email.sender_name} <{email.sender_email}>",
        f"Temat: {email.subject}",
        f"Otrzymano: {email.received_at.isoformat()}",
        "",
        "--- text_content (PEŁNA TREŚĆ — przeczytaj do końca) ---",
        email.text_content,
        "",
        "--- raw_links (backup linków z HTML) ---",
    ]
    if email.raw_links:
        for rl in email.raw_links:
            parts.append(f"- {rl.get('text', '')[:80]} → {rl.get('url', '')}")
    else:
        parts.append("(brak)")
    parts.append("")
    parts.append("Wywołaj teraz narzędzie `emit_newsletter_topics` z wyekstrahowanymi tematami.")
    return "\n".join(parts)


def _extract_single_newsletter(
    client: Anthropic,
    cfg: Config,
    idx: int,
    email: FetchedEmail,
    debug_dir: Path | None,
    retry_attempt: bool = False,
    accumulated_input_tokens: int = 0,
    accumulated_output_tokens: int = 0,
    accumulated_cost_usd: float = 0.0,
) -> DigestNewsletter:
    """Stage 1: extract topics from a single newsletter via LLM."""
    user_content = _build_stage1_message(email)
    log.info(
        "Stage1 call: model=%s idx=%d sender=%r input_chars=%d",
        cfg.anthropic_model_stage1, idx, email.sender_name, len(user_content),
    )

    t0 = time.monotonic()
    # Non-streaming: each newsletter takes <5 min so no 10-min timeout issue.
    # Using non-streaming avoids a streaming SDK quirk where large tool_use inputs
    # arrive as a raw JSON string instead of a parsed dict.
    system_prompt = STAGE1_RETRY_SYSTEM_PROMPT if retry_attempt else STAGE1_SYSTEM_PROMPT
    response = client.messages.create(
        model=cfg.anthropic_model_stage1,
        max_tokens=STAGE1_MAX_OUTPUT_TOKENS,
        system=[{
            "type": "text",
            "text": system_prompt,
            "cache_control": {"type": "ephemeral"},
        }],
        tools=[STAGE1_TOOL_SCHEMA],
        tool_choice={"type": "tool", "name": "emit_newsletter_topics"},
        messages=[{"role": "user", "content": user_content}],
        timeout=300,  # 5-minute hard timeout per newsletter
    )
    elapsed = time.monotonic() - t0

    log.info(
        "Stage1 response: idx=%d sender=%r elapsed=%.1fs stop_reason=%s "
        "usage_in=%s usage_out=%s cache_read=%s cache_write=%s",
        idx, email.sender_name, elapsed, response.stop_reason,
        response.usage.input_tokens, response.usage.output_tokens,
        getattr(response.usage, "cache_read_input_tokens", None),
        getattr(response.usage, "cache_creation_input_tokens", None),
    )
    call_input_tokens = int(getattr(response.usage, "input_tokens", 0) or 0)
    call_output_tokens = int(getattr(response.usage, "output_tokens", 0) or 0)
    call_cache_write_tokens = int(getattr(response.usage, "cache_creation_input_tokens", 0) or 0)
    call_cache_read_tokens = int(getattr(response.usage, "cache_read_input_tokens", 0) or 0)
    call_cost_usd = _estimate_cost_usd(
        call_input_tokens,
        call_output_tokens,
        cfg.stage1_input_usd_per_mtok,
        cfg.stage1_output_usd_per_mtok,
        cache_write_tokens=call_cache_write_tokens,
        cache_read_tokens=call_cache_read_tokens,
        cache_write_per_mtok=cfg.stage1_cache_write_usd_per_mtok,
        cache_read_per_mtok=cfg.stage1_cache_read_usd_per_mtok,
    )
    total_input_tokens = accumulated_input_tokens + call_input_tokens
    total_output_tokens = accumulated_output_tokens + call_output_tokens
    total_cost_usd = accumulated_cost_usd + call_cost_usd
    if response.stop_reason == "max_tokens":
        log.warning(
            "Stage1 idx=%d sender=%r hit max_tokens (%d) — output was truncated, topics may be empty. "
            "Consider increasing STAGE1_MAX_OUTPUT_TOKENS or switching to a model with higher output limit.",
            idx, email.sender_name, STAGE1_MAX_OUTPUT_TOKENS,
        )

    tool_use = next((b for b in response.content if getattr(b, "type", None) == "tool_use"), None)

    if debug_dir is not None:
        debug_dir.mkdir(parents=True, exist_ok=True)
        suffix = "-retry" if retry_attempt else ""
        (debug_dir / f"stage1-idx{idx}{suffix}.json").write_text(
            json.dumps(
                {"idx": idx, "sender": email.sender_name, "tool_input": tool_use.input if tool_use else None},
                ensure_ascii=False, indent=2,
            ),
            encoding="utf-8",
        )

    if tool_use is None:
        if not retry_attempt:
            log.warning(
                "Stage1 idx=%d sender=%r: no tool_use on first attempt — retrying once",
                idx,
                email.sender_name,
            )
            return _extract_single_newsletter(
                client=client,
                cfg=cfg,
                idx=idx,
                email=email,
                debug_dir=debug_dir,
                retry_attempt=True,
                accumulated_input_tokens=total_input_tokens,
                accumulated_output_tokens=total_output_tokens,
                accumulated_cost_usd=total_cost_usd,
            )
        log.warning("Stage1 idx=%d sender=%r: no tool_use after retry — inserting empty newsletter", idx, email.sender_name)
        return DigestNewsletter(
            sender=email.sender_name or email.sender_email,
            subject=email.subject,
            topics=[],
            original_index=idx,
            estimated_cost_usd=total_cost_usd,
            stage1_input_tokens=total_input_tokens,
            stage1_output_tokens=total_output_tokens,
        )

    data = tool_use.input or {}
    raw_topics = data.get("topics", []) or []
    # Guard: model sometimes returns topics as JSON-encoded string instead of parsed list.
    # Summaries with literal newlines inside strings make the JSON technically invalid, so
    # we try strict mode first, then lenient mode (strict=False allows control chars in strings).
    if isinstance(raw_topics, str):
        parsed_topics = None
        try:
            parsed_topics = json.loads(raw_topics)
        except json.JSONDecodeError as exc:
            sanitized = _sanitize_json_control_chars(raw_topics)
            try:
                parsed_topics = json.loads(sanitized)
            except json.JSONDecodeError:
                log.warning(
                    "Stage1 idx=%d sender=%r: topics JSON parse failed at pos=%d (%s). first_120=%r",
                    idx, email.sender_name, exc.pos, exc.msg, raw_topics[:120],
                )
        if isinstance(parsed_topics, list):
            raw_topics = parsed_topics
            log.debug(
                "Stage1 idx=%d sender=%r: topics was JSON string — parsed %d items",
                idx, email.sender_name, len(raw_topics),
            )
        else:
            repaired, repair_in, repair_out, repair_cost = _repair_topics_with_llm(client, cfg, raw_topics, idx, email.sender_name)
            total_input_tokens += repair_in
            total_output_tokens += repair_out
            total_cost_usd += repair_cost
            if repaired:
                raw_topics = repaired
                log.info(
                    "Stage1 idx=%d sender=%r: topics repaired via LLM fallback (%d items)",
                    idx, email.sender_name, len(raw_topics),
                )
            else:
                raw_topics = []

    topics: list[DigestTopic] = []
    for t in raw_topics:
        if not isinstance(t, dict):
            continue
        title = (t.get("title") or "").strip()
        summary = (t.get("summary") or "").strip()
        if not title or not summary:
            continue
        links = [lk for lk in (t.get("links") or []) if isinstance(lk, dict) and lk.get("url")]
        topics.append(DigestTopic(title=title, summary=summary, links=links))

    sender = (data.get("sender") or "").strip() or email.sender_name or email.sender_email
    subject = (data.get("subject") or "").strip() or email.subject
    if not topics and not retry_attempt:
        log.warning(
            "Stage1 idx=%d sender=%r: zero parsed topics on first attempt — retrying once",
            idx,
            email.sender_name,
        )
        return _extract_single_newsletter(
            client=client,
            cfg=cfg,
            idx=idx,
            email=email,
            debug_dir=debug_dir,
            retry_attempt=True,
            accumulated_input_tokens=total_input_tokens,
            accumulated_output_tokens=total_output_tokens,
            accumulated_cost_usd=total_cost_usd,
        )
    return DigestNewsletter(
        sender=sender,
        subject=subject,
        topics=topics,
        original_index=idx,
        estimated_cost_usd=total_cost_usd,
        stage1_input_tokens=total_input_tokens,
        stage1_output_tokens=total_output_tokens,
    )


def _build_stage2_message(newsletters: list[DigestNewsletter]) -> str:
    payload = []
    for nl in newsletters:
        payload.append({
            "newsletter_idx": nl.original_index,
            "sender": nl.sender,
            "topics": [
                {"topic_idx": i, "title": t.title, "summary": t.summary}
                for i, t in enumerate(nl.topics)
            ],
        })
    return (
        "Poniżej kompaktowe podsumowanie wszystkich newsletterów dnia. "
        "Zidentyfikuj tematy, które dotyczą dokładnie tego samego zdarzenia/artykułu.\n\n"
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + "\n\nWywołaj teraz narzędzie `emit_dedup_assignments`."
    )


def _sender_key(email: FetchedEmail) -> str:
    sender_email = (email.sender_email or "").strip().lower()
    sender_name = (email.sender_name or "").strip().lower()
    return sender_email or sender_name or "unknown-sender"


def _load_sender_profiles(cfg: Config) -> dict[str, dict]:
    path = cfg.data_dir / "digests" / SENDER_PROFILE_FILE
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        log.warning("Sender profile file is malformed: %s", path)
        return {}
    if isinstance(data, dict):
        return data
    return {}


def _save_sender_profiles(cfg: Config, profiles: dict[str, dict]) -> None:
    path = cfg.data_dir / "digests" / SENDER_PROFILE_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(profiles, ensure_ascii=False, indent=2), encoding="utf-8")


def _should_trust_rules_for_sender(profile: dict) -> bool:
    good = int(profile.get("rule_good_runs", 0) or 0)
    bad = int(profile.get("rule_bad_runs", 0) or 0)
    total = good + bad
    if total < 3:
        return False
    bad_ratio = bad / total if total > 0 else 1.0
    return good >= 3 and bad_ratio <= 0.20


def _rule_is_acceptable_for_trusted_sender(topics: list[RuleTopic]) -> bool:
    if not topics:
        return False
    linked = sum(1 for t in topics if t.links)
    if linked / max(len(topics), 1) < 0.60:
        return False
    summary_words = [len((t.summary or "").split()) for t in topics]
    if not summary_words:
        return False
    return max(summary_words) >= 8


def _rule_newsletter_from_email(idx: int, email: FetchedEmail) -> DigestNewsletter:
    rule_topics = extract_rule_topics(
        email.text_content,
        email.raw_links,
        sender_name=email.sender_name,
        sender_email=email.sender_email,
    )
    topics = [DigestTopic(title=t.title, summary=t.summary, links=t.links) for t in rule_topics]
    return DigestNewsletter(
        sender=email.sender_name or email.sender_email,
        subject=email.subject,
        topics=topics,
        original_index=idx,
        estimated_cost_usd=0.0,
        stage1_input_tokens=0,
        stage1_output_tokens=0,
        processed_with="rules",
    )


def _english_text_density(text: str) -> float:
    tokens = re.findall(r"[a-z]{2,}", (text or "").lower())
    if not tokens:
        return 0.0
    english_hits = sum(1 for token in tokens if token in ENGLISH_HINT_WORDS)
    return english_hits / len(tokens)


def _should_route_for_translation(email: FetchedEmail, newsletter: DigestNewsletter) -> bool:
    """Route to LLM only for long single-topic English newsletters (e.g., EXANTE/Naval)."""
    sender_blob = f"{email.sender_name} {email.sender_email} {email.subject}".lower()
    if not any(hint in sender_blob for hint in TRANSLATION_SENDER_HINTS):
        return False
    topic_count = len(newsletter.topics)
    if topic_count < 1 or topic_count > 3:
        return False
    if len(email.text_content or "") < 3500:
        return False
    sample = " ".join(
        [email.subject] + [f"{topic.title} {topic.summary}" for topic in newsletter.topics]
    )
    sample = f"{sample}\n{(email.text_content or '')[:3000]}"
    return _english_text_density(sample) >= 0.06


def _should_force_llm_for_semantic_segmentation(email: FetchedEmail) -> bool:
    sender_blob = f"{email.sender_name} {email.sender_email}".lower()
    if any(hint in sender_blob for hint in SEMANTIC_SEGMENTATION_SENDERS):
        return True
    return False


def _tokenize_for_link_backfill(text: str) -> set[str]:
    return {w.lower() for w in TOKEN_RE.findall(text or "")}


def _backfill_missing_topic_links(newsletter: DigestNewsletter, email: FetchedEmail) -> None:
    used_urls = {
        lk.get("url", "")
        for topic in newsletter.topics
        for lk in topic.links
        if isinstance(lk, dict) and lk.get("url")
    }
    for topic in newsletter.topics:
        if topic.links:
            continue
        topic_tokens = _tokenize_for_link_backfill(topic.title + " " + topic.summary)
        best_link: dict | None = None
        best_score = -1
        for idx, lk in enumerate(email.raw_links):
            url = (lk.get("url") or "").strip()
            text = (lk.get("text") or "").strip()
            if not url or url in used_urls:
                continue
            link_tokens = _tokenize_for_link_backfill(text)
            overlap = len(topic_tokens & link_tokens)
            score = overlap * 10 + max(0, 5 - idx)
            if score > best_score:
                best_score = score
                best_link = {"text": text[:120] or "Źródło", "url": url}
        if best_link is not None:
            topic.links = [best_link]
            used_urls.add(best_link["url"])


def _apply_dedup_assignments(newsletters: list[DigestNewsletter], assignments: list[dict], source: str) -> list[DigestNewsletter]:
    nl_by_idx: dict[int, DigestNewsletter] = {nl.original_index: nl for nl in newsletters}
    applied = 0
    for a in assignments:
        if not isinstance(a, dict):
            continue
        try:
            nl_idx = int(a["newsletter_idx"])
            topic_idx = int(a["topic_idx"])
            dup_of = int(a["duplicate_of_newsletter_idx"])
        except (KeyError, TypeError, ValueError):
            log.debug("%s: malformed assignment %r — skipped", source, a)
            continue
        nl = nl_by_idx.get(nl_idx)
        if nl is None:
            log.debug("%s: unknown newsletter_idx=%d — skipped", source, nl_idx)
            continue
        if topic_idx < 0 or topic_idx >= len(nl.topics):
            log.debug("%s: topic_idx=%d out of range for newsletter_idx=%d — skipped", source, topic_idx, nl_idx)
            continue
        if dup_of == nl_idx:
            log.debug("%s: self-reference assignment (newsletter_idx=%d) — skipped", source, nl_idx)
            continue
        nl.topics[topic_idx].duplicate_of = dup_of
        applied += 1
    log.info("%s: applied %d duplicate marking(s)", source, applied)
    return newsletters


def _run_rule_dedup(newsletters: list[DigestNewsletter], date: str) -> list[DigestNewsletter]:
    if len(newsletters) <= 1:
        log.info("Rule dedup: skipped (only %d newsletter)", len(newsletters))
        return newsletters
    payload = [
        {
            "newsletter_idx": nl.original_index,
            "topics": [{"title": t.title, "summary": t.summary, "links": t.links} for t in nl.topics],
        }
        for nl in newsletters
    ]
    assignments = compute_rule_dedup_assignments(payload)
    log.info("Rule dedup: date=%s received %d assignment(s)", date, len(assignments))
    return _apply_dedup_assignments(newsletters, assignments, "Rule dedup")


def _run_stage2_dedup(
    client: Anthropic,
    cfg: Config,
    newsletters: list[DigestNewsletter],
    date: str,
    debug_dir: Path | None,
) -> list[DigestNewsletter]:
    """Stage 2: mark cross-newsletter duplicate topics. Returns newsletters unchanged on failure."""
    if len(newsletters) <= 1:
        log.info("Stage2: skipped (only %d newsletter)", len(newsletters))
        return newsletters

    total_topics = sum(len(nl.topics) for nl in newsletters)
    if total_topics == 0:
        log.info("Stage2: skipped (no topics to dedup)")
        return newsletters

    user_content = _build_stage2_message(newsletters)
    log.info(
        "Stage2 call: model=%s date=%s newsletters=%d total_topics=%d input_chars=%d",
        cfg.anthropic_model_stage2, date, len(newsletters), total_topics, len(user_content),
    )

    t0 = time.monotonic()
    try:
        with client.messages.stream(
            model=cfg.anthropic_model_stage2,
            max_tokens=STAGE2_MAX_OUTPUT_TOKENS,
            system=[{
                "type": "text",
                "text": STAGE2_SYSTEM_PROMPT,
                "cache_control": {"type": "ephemeral"},
            }],
            tools=[STAGE2_TOOL_SCHEMA],
            tool_choice={"type": "tool", "name": "emit_dedup_assignments"},
            messages=[{"role": "user", "content": user_content}],
        ) as stream:
            response = stream.get_final_message()
    except Exception:
        log.exception("Stage2 dedup call failed — returning digest without deduplication")
        return newsletters

    elapsed = time.monotonic() - t0
    log.info(
        "Stage2 response: elapsed=%.1fs stop_reason=%s usage_in=%s usage_out=%s",
        elapsed, response.stop_reason, response.usage.input_tokens, response.usage.output_tokens,
    )

    tool_use = next((b for b in response.content if getattr(b, "type", None) == "tool_use"), None)

    if debug_dir is not None:
        debug_dir.mkdir(parents=True, exist_ok=True)
        (debug_dir / f"stage2-{date}.json").write_text(
            json.dumps(
                {"tool_input": tool_use.input if tool_use else None},
                ensure_ascii=False, indent=2,
            ),
            encoding="utf-8",
        )

    if tool_use is None:
        log.warning("Stage2: no tool_use in response — skipping deduplication")
        return newsletters

    assignments = (tool_use.input or {}).get("assignments", []) or []
    log.info("Stage2: received %d duplicate assignment(s)", len(assignments))

    return _apply_dedup_assignments(newsletters, assignments, "Stage2")


def make_anthropic_client(cfg: Config) -> Anthropic:
    """Create a single Anthropic client to be reused across multiple generate_digest calls."""
    if not cfg.anthropic_api_key:
        raise RuntimeError("ANTHROPIC_API_KEY is required for selected processing mode")
    return Anthropic(api_key=cfg.anthropic_api_key)


def generate_digest(
    cfg: Config,
    date: str,
    emails: list[FetchedEmail],
    client: Anthropic | None = None,
    processing_mode: ProcessingMode | None = None,
) -> Digest | None:
    if not emails:
        return None

    mode: ProcessingMode = processing_mode or cfg.processing_mode
    if mode in ("llm-only", "hybrid") and client is None:
        client = make_anthropic_client(cfg)
    debug_dir = cfg.data_dir / "digests" / "raw"
    sender_profiles = _load_sender_profiles(cfg)

    # Stage 1: extract topics
    t_start = time.monotonic()
    assembled: list[DigestNewsletter] = []

    if mode == "no-llm":
        log.info("Stage1 start (rule-only): %d newsletters", len(emails))
        assembled = [_rule_newsletter_from_email(idx, email) for idx, email in enumerate(emails)]
    elif mode == "llm-only":
        assert client is not None
        log.info(
            "Stage1 start (llm-only): %d newsletters, model=%s, max_workers=%d",
            len(emails), cfg.anthropic_model_stage1, cfg.stage1_max_workers,
        )
        newsletters_llm: list[DigestNewsletter | None] = [None] * len(emails)
        max_workers = min(len(emails), cfg.stage1_max_workers)

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(_extract_single_newsletter, client, cfg, idx, email, debug_dir): idx
                for idx, email in enumerate(emails)
            }
            for future in as_completed(futures):
                idx = futures[future]
                try:
                    nl = future.result()
                    nl.processed_with = "llm"
                except Exception:
                    log.exception(
                        "Stage1 extraction failed for idx=%d sender=%r — inserting empty placeholder",
                        idx, emails[idx].sender_name,
                    )
                    nl = DigestNewsletter(
                        sender=emails[idx].sender_name or emails[idx].sender_email,
                        subject=emails[idx].subject,
                        topics=[],
                        original_index=idx,
                        processed_with="llm",
                    )
                newsletters_llm[idx] = nl

        for i, nl in enumerate(newsletters_llm):
            if nl is None:
                log.error("Stage1: newsletter slot %d is still None — inserting empty placeholder", i)
                newsletters_llm[i] = DigestNewsletter(
                    sender=emails[i].sender_name or emails[i].sender_email,
                    subject=emails[i].subject,
                    topics=[],
                    original_index=i,
                    processed_with="llm",
                )
        assembled = newsletters_llm  # type: ignore[assignment]
    else:
        assert client is not None
        log.info(
            "Stage1 start (hybrid): %d newsletters, llm_model=%s, max_workers=%d",
            len(emails), cfg.anthropic_model_stage1, cfg.stage1_max_workers,
        )
        hybrid_newsletters: list[DigestNewsletter] = [
            _rule_newsletter_from_email(idx, email) for idx, email in enumerate(emails)
        ]
        fallback_indices: list[int] = []
        fallback_reason_by_idx: dict[int, str] = {}
        for idx, nl in enumerate(hybrid_newsletters):
            email = emails[idx]
            sender_key = _sender_key(email)
            profile = sender_profiles.get(sender_key, {})
            rule_topics = [RuleTopic(title=t.title, summary=t.summary, links=t.links) for t in nl.topics]
            readability = evaluate_human_readability(rule_topics)
            base_sufficient = rule_output_is_sufficient(
                rule_topics,
                raw_link_count=len(email.raw_links),
                sender_name=email.sender_name,
                sender_email=email.sender_email,
            )
            if _should_trust_rules_for_sender(profile):
                if not _rule_is_acceptable_for_trusted_sender(rule_topics):
                    fallback_indices.append(idx)
                    fallback_reason_by_idx[idx] = "trusted-quality-guard"
            elif not base_sufficient:
                fallback_indices.append(idx)
                fallback_reason_by_idx[idx] = "quality-threshold"
            elif readability.score < 0.70 or readability.unreadable_topics > 0:
                fallback_indices.append(idx)
                fallback_reason_by_idx[idx] = "human-readability"
            elif _should_force_llm_for_semantic_segmentation(email):
                fallback_indices.append(idx)
                fallback_reason_by_idx[idx] = "semantic-segmentation"
            elif _should_route_for_translation(email, nl):
                fallback_indices.append(idx)
                fallback_reason_by_idx[idx] = "translation-single-topic"
        if fallback_indices:
            fallback_senders = [
                f"{emails[idx].sender_name}:{fallback_reason_by_idx.get(idx, 'unknown')}"
                for idx in fallback_indices
            ]
            log.info(
                "Stage1 hybrid: %d/%d newsletters require LLM fallback senders=%s",
                len(fallback_indices),
                len(emails),
                fallback_senders,
            )
        else:
            log.info("Stage1 hybrid: 0/%d newsletters require LLM fallback", len(emails))
        if fallback_indices:
            max_workers = min(len(fallback_indices), cfg.stage1_max_workers)
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = {
                    executor.submit(
                        _extract_single_newsletter, client, cfg, idx, emails[idx], debug_dir
                    ): idx
                    for idx in fallback_indices
                }
                for future in as_completed(futures):
                    idx = futures[future]
                    try:
                        llm_nl = future.result()
                        llm_nl.processed_with = "llm"
                        rule_nl = hybrid_newsletters[idx]
                        llm_linked_topics = sum(1 for t in llm_nl.topics if t.links)
                        rule_linked_topics = sum(1 for t in rule_nl.topics if t.links)
                        llm_too_weak = (
                            (not llm_nl.topics and bool(rule_nl.topics))
                            or (llm_linked_topics == 0 and rule_linked_topics > 0)
                            or (
                                len(rule_nl.topics) >= 6
                                and len(llm_nl.topics) < max(1, len(rule_nl.topics) // 3)
                            )
                        )
                        if llm_too_weak:
                            log.warning(
                                "Stage1 hybrid fallback weak for idx=%d sender=%r (rule_topics=%d llm_topics=%d) — keeping rule output",
                                idx,
                                emails[idx].sender_name,
                                len(rule_nl.topics),
                                len(llm_nl.topics),
                            )
                        else:
                            hybrid_newsletters[idx] = llm_nl
                    except Exception:
                        log.exception(
                            "Stage1 hybrid fallback failed for idx=%d sender=%r — keeping rule output",
                            idx, emails[idx].sender_name,
                        )
        assembled = hybrid_newsletters

    t_stage1 = time.monotonic()
    for idx, nl in enumerate(assembled):
        _backfill_missing_topic_links(nl, emails[idx])
        sender_key = _sender_key(emails[idx])
        profile = sender_profiles.setdefault(
            sender_key,
            {
                "sender_name": emails[idx].sender_name or emails[idx].sender_email,
                "rule_good_runs": 0,
                "rule_bad_runs": 0,
                "llm_runs": 0,
                "last_mode": "",
                "last_processed_with": "",
            },
        )
        if nl.processed_with == "llm":
            profile["llm_runs"] = int(profile.get("llm_runs", 0) or 0) + 1
            profile["rule_bad_runs"] = int(profile.get("rule_bad_runs", 0) or 0) + 1
        else:
            quality_ok = rule_output_is_sufficient(
                [RuleTopic(title=t.title, summary=t.summary, links=t.links) for t in nl.topics],
                raw_link_count=len(emails[idx].raw_links),
                sender_name=emails[idx].sender_name,
                sender_email=emails[idx].sender_email,
            )
            if quality_ok:
                profile["rule_good_runs"] = int(profile.get("rule_good_runs", 0) or 0) + 1
            else:
                profile["rule_bad_runs"] = int(profile.get("rule_bad_runs", 0) or 0) + 1
        profile["last_mode"] = mode
        profile["last_processed_with"] = nl.processed_with

    _save_sender_profiles(cfg, sender_profiles)

    log.info(
        "Stage1 complete: mode=%s elapsed=%.1fs newsletters=%d total_topics=%d",
        mode, t_stage1 - t_start, len(assembled), sum(len(n.topics) for n in assembled),
    )

    # Stage 2: cross-newsletter deduplication
    if mode in ("llm-only", "hybrid"):
        assert client is not None
        assembled = _run_stage2_dedup(client, cfg, assembled, date, debug_dir)
    else:
        assembled = _run_rule_dedup(assembled, date)
    t_stage2 = time.monotonic()
    log.info(
        "Stage2 complete: mode=%s elapsed=%.1fs",
        mode, t_stage2 - t_stage1,
    )

    digest = Digest(date=date, newsletters=assembled, processing_mode=mode)
    log.info(
        "Digest assembled: newsletters=%d topics=%d duplicates=%d empty_newsletters=%d est_cost_usd=%.6f "
        "stage1=%.1fs stage2=%.1fs total=%.1fs",
        len(digest.newsletters),
        digest.topic_count,
        digest.duplicate_count,
        sum(1 for n in digest.newsletters if not n.topics),
        digest.estimated_cost_usd,
        t_stage1 - t_start,
        t_stage2 - t_stage1,
        t_stage2 - t_start,
    )
    return digest


def digest_to_json(digest: Digest) -> str:
    payload = {
        "date": digest.date,
        "processing_mode": digest.processing_mode,
        "newsletters": [
            {
                "original_index": n.original_index,
                "sender": n.sender,
                "subject": n.subject,
                "estimated_cost_usd": n.estimated_cost_usd,
                "stage1_input_tokens": n.stage1_input_tokens,
                "stage1_output_tokens": n.stage1_output_tokens,
                "processed_with": n.processed_with,
                "topics": [
                    {
                        "title": t.title,
                        "summary": t.summary,
                        "links": t.links,
                        "duplicate_of": t.duplicate_of,
                    }
                    for t in n.topics
                ],
            }
            for n in digest.newsletters
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)
